# use ubuntu base image
FROM ubuntu:20.04

WORKDIR /code
VOLUME /code/shared
VOLUME /var/log/nginx

# install dependencies
RUN apt-get update && \
    apt-get install nginx-light openssl -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# create self-signed certificates
RUN mkdir -p /usr/local/ssl/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -subj "/CN=DReSA/O=Digital Research Skills Australasia/C=AU" \
    -keyout /usr/local/ssl/certs/nginx-self-signed.key \
    -out /usr/local/ssl/certs/nginx-self-signed.crt && \
    openssl dhparam -out /etc/nginx/dhparam.pem 4096

# start nginx
EXPOSE 80 443

ENTRYPOINT ["docker/entrypoint_nginx.sh"]

CMD ["nginx", "-g", "daemon off;"]

# --- end of file --- #